import { describe, expect, it } from 'vitest'
import type { Transaction } from '../data/models'
import { buildSourceCategoryGroups, categorize, classifyType, isGasSourceCategory, isPaid, isSpending, normalizeMerchant, parseAmount, parseDate, processStatement, sourceCategoryChild, sourceCategoryGroup } from './statementImport'
import { accounts, categories } from '../data/mockData'
import { classifyDocument, detectPdfCandidates } from './pdfPipeline'

describe('statement normalization helpers', () => {
  it('parses common amount formats', () => { expect(parseAmount('$1,234.56')).toBe(1234.56); expect(parseAmount('(42.18)')).toBe(-42.18); expect(parseAmount('1,000.00 CR')).toBe(-1000); expect(parseAmount('1,000.00 DR')).toBe(1000); expect(parseAmount('not money')).toBeUndefined() })
  it('parses financial date formats', () => { expect(parseDate('08/14/2026')).toBe('2026-08-14'); expect(parseDate('01/07/26')).toBe('2026-01-07'); expect(parseDate('Aug 8, 2026')).toBe('2026-08-08'); expect(parseDate('Jan 22, 2026')).toBe('2026-01-22'); expect(parseDate('2026-08-14')).toBe('2026-08-14') })
  it('keeps raw-derived merchant normalizations conservative', () => { expect(normalizeMerchant('DUNKIN #1234 DES MOINES IA').name).toBe('Dunkin'); expect(normalizeMerchant('AMZN MKTP US*123').name).toBe('Amazon'); expect(normalizeMerchant('AplPay BUZ COFFEE & DUBUQUE IA').name).toBe('Buz Coffee'); expect(normalizeMerchant('SQ *BUZ COFFEE & ENERG DUBUQUE IA').name).toBe('Buz Coffee') })
  it('groups hierarchical source categories by their parent for any provider labels', () => { expect(sourceCategoryGroup('Merchandise and Supplies - Internet Purchase')).toBe('Merchandise and Supplies'); expect(sourceCategoryChild('Merchandise and Supplies - Internet Purchase')).toBe('Internet Purchase'); expect(sourceCategoryGroup('General Purchase - Mail Order')).toBe('General Purchase'); expect(sourceCategoryChild('General Purchase - Mail Order')).toBe('Mail Order'); expect(sourceCategoryChild('Merchandise and Supplies: Groceries')).toBe('Groceries'); expect(sourceCategoryGroup('Payments and Credits')).toBe('Payments and Credits'); expect(sourceCategoryChild('Payments and Credits')).toBeUndefined() })
  it('recognizes provider-specific gas labels as one normalized source', () => { expect(isGasSourceCategory('Gasoline')).toBe(true); expect(isGasSourceCategory('Gas')).toBe(true); expect(isGasSourceCategory('Transportation-Fuel')).toBe(true); expect(isGasSourceCategory('Transportation-Auto Services')).toBe(false); expect(isGasSourceCategory('Utilities-Natural Gas')).toBe(false) })
  it('derives only the source children present in the supplied visible rows', () => {
    const base: Transaction = { id: 'base', accountId: 'a', statementId: 's', transactionDate: '2026-08-01', merchantRaw: 'merchant', merchantNormalized: 'Merchant', description: 'merchant', amount: 10, currency: 'USD', categoryId: 'shopping', subcategory: '', transactionType: 'purchase', sourceFile: 'test.csv', confidence: 1 }
    const groups = buildSourceCategoryGroups([
      { ...base, id: 'mail', sourceCategory: 'Merchandise & Supplies-Mail Order' },
      { ...base, id: 'grocery', sourceCategory: 'Merchandise & Supplies-Groceries' },
    ])
    expect(groups).toEqual([{ key: 'merchandise & supplies', parent: 'Merchandise & Supplies', children: [{ key: 'mail order', label: 'Mail Order' }, { key: 'groceries', label: 'Groceries' }] }])
    expect(buildSourceCategoryGroups([{ ...base, sourceCategory: 'Merchandise & Supplies-Mail Order' }])[0].children).toEqual([{ key: 'mail order', label: 'Mail Order' }])
  })
  it('prioritizes a source-provided category over merchant inference', () => { expect(categorize('Amazon', categories, 'Restaurant-Bar & Café').categoryId).toBe('food'); expect(categorize('Unknown merchant', categories, 'Transportation-Fuel').categoryId).toBe('transport'); expect(categorize('Unknown merchant', categories, 'Fees & Adjustments-Fees & Adjustments').categoryId).toBe('fees') })
  it('applies case-insensitive grocery overrides for noisy retailer descriptions', () => { expect(categorize('#1234 WALMART', categories, 'Merchandise').categoryId).toBe('groceries'); expect(categorize('WALMART.COM', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('POS *KROGER 8842', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('TGT TARGET STORE T-', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('WM SUPERCENTER #3762', categories, 'Groceries').categoryId).toBe('groceries'); expect(categorize('wAl-MaRt', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('ALDI US #123', categories, 'Other').categoryId).toBe('groceries'); expect(categorize("CARD PURCHASE SAM'S CLUB 123", categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('Costco Wholesale', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('AplPay WALMART #1234', categories, 'Shopping').categoryId).toBe('groceries'); expect(categorize('AplPay MAVERIK #5020', categories, 'Gas').categoryId).not.toBe('groceries') })
  it('identifies payments and refunds from transaction context', () => { expect(classifyType('AUTOPAY PAYMENT', 500)).toBe('payment'); expect(classifyType('MERCHANT REFUND', 42)).toBe('refund'); expect(classifyType('STORE', -42)).toBe('purchase') })
  it('excludes card payments and refunds from spending totals', () => { const base = { id:'1',accountId:'a',statementId:'s',transactionDate:'2026-08-14',merchantRaw:'x',merchantNormalized:'x',description:'x',amount:10,currency:'USD' as const,categoryId:'food',subcategory:'',sourceFile:'x',confidence:1 }; const entries: Transaction[] = [{...base,transactionType:'purchase'}, {...base,id:'2',transactionType:'payment',amount:500}, {...base,id:'3',transactionType:'refund',amount:-10}]; expect(entries.filter(isSpending).reduce((sum,t)=>sum+Math.abs(t.amount),0)).toBe(10) })
  it('does not treat generic transfers as paid card payments', () => { const transfer: Transaction = { id:'transfer',accountId:'a',statementId:'s',transactionDate:'2026-08-14',merchantRaw:'Amex Send: Transfer to Card',merchantNormalized:'Amex Send',description:'Amex Send: Transfer to Card',amount:-350,currency:'USD',categoryId:'other',subcategory:'',sourceFile:'x',confidence:1,transactionType:'transfer' }; expect(isPaid(transfer)).toBe(false); expect(isSpending(transfer)).toBe(false) })
  it('parses CSV statements and stops duplicate imports', async () => { const file = new File(['Transaction Date,Description,Amount\n08/14/2026,DUNKIN #1234,$12.42\n08/15/2026,AUTOPAY PAYMENT,$500.00'], 'capital one august.csv', { type: 'text/csv' }); const first = await processStatement(file, accounts, categories, []); expect(first.statement.transactionCount).toBe(2); expect(first.transactions[0].transaction.merchantNormalized).toBe('Dunkin'); expect(first.transactions[1].transaction.transactionType).toBe('payment'); const duplicate = await processStatement(file, accounts, categories, [first.statement.fingerprint]); expect(duplicate.statement.status).toBe('duplicate') })
  it('inverts Chase CSV signs without changing other providers', async () => { const file = new File(['Transaction Date,Description,Amount\n08/14/2026,DUNKIN #1234,-$12.42\n08/15/2026,PAYMENT THANK YOU,$500.00'], 'Chase3491_Activity.csv', { type: 'text/csv' }); const result = await processStatement(file, accounts, categories, []); expect(result.statement.accountId).toBe('chase'); expect(result.transactions[0].transaction.amount).toBe(12.42); expect(result.transactions[1].transaction.amount).toBe(-500) })
  it('classifies sanitized PDF report structures without inventing transactions', () => { expect(classifyDocument('Discover Year-to-Date Summary\nSpending by Category')).toBe('YEAR_TO_DATE_SUMMARY'); expect(classifyDocument('Spending Report\nCategory spending')).toBe('SPENDING_REPORT'); expect(classifyDocument('American Express\nAccount Activity\nTransactions')).toBe('TRANSACTION_STATEMENT') })
  it('reconstructs wrapped transaction rows inside a detected activity section', () => { const rows = [{ text: 'Account Activity', page: 1 }, { text: '08/12/2026', page: 1 }, { text: 'DUNKIN #1234 DES', page: 1 }, { text: 'MOINES IA', page: 1 }, { text: '$12.42', page: 1 }, { text: '08/13/2026 UBER TRIP $24.13', page: 1 }, { text: 'Account Summary', page: 1 }, { text: 'Statement balance $1,244.00', page: 1 }]; expect(detectPdfCandidates(rows, 'activity.pdf').map(item => item.rawDescription)).toEqual(['DUNKIN #1234 DES MOINES IA', 'UBER TRIP']); expect(detectPdfCandidates(rows, 'activity.pdf')).toHaveLength(2) })
})
