import { useEffect, useRef, useState } from 'react'
import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, ChevronUp, FileSpreadsheet, FileWarning, LoaderCircle, Plus, RotateCcw, ShieldCheck, Trash2, Upload, X } from 'lucide-react'
import type { Account, Category, ImportResult, ImportStatus, ReviewTransaction, Statement } from '../data/models'
import { processStatement } from '../services/statementImport'
import OnboardingTour, { type TourStep } from './OnboardingTour'

type Props = { accounts: Account[]; categories: Category[]; importedStatements: Statement[]; tourStep?: TourStep; tourScope?: 'full'|'current'|null; onTourStep?: (step: TourStep) => void; onTourSkip?: () => void; onTourFinish?: () => void; onTourBack?: () => void; onTourStart?: (scope: 'full'|'current') => void; onBack: () => void; onComplete: (transactions: ReviewTransaction[], statements: Statement[]) => void }
const labels: Record<ImportStatus, string> = { queued: 'Queued', processing: 'Analyzing', ready: 'Ready', warning: 'Needs review', failed: 'Could not import', imported: 'Imported', duplicate: 'Potential duplicate' }
const fileSize = (bytes: number) => `${(bytes / 1024).toFixed(bytes > 1024 * 1024 ? 1 : 0)} ${bytes > 1024 * 1024 ? 'MB' : 'KB'}`

export default function ImportFlow({ accounts, categories, importedStatements, tourStep = 'idle', tourScope = null, onTourStep, onTourSkip, onTourFinish, onTourBack, onTourStart, onBack, onComplete }: Props) {
  const picker = useRef<HTMLInputElement>(null); const reviewBottom = useRef<HTMLDivElement>(null); const [imports, setImports] = useState<ImportResult[]>([]); const [dragging, setDragging] = useState(false); const [step, setStep] = useState<'upload'|'review'|'complete'>('upload'); const [importedCount, setImportedCount] = useState(0); const [showCompletion, setShowCompletion] = useState(false); const [showImportNext, setShowImportNext] = useState(false)
  useEffect(() => { if (step !== 'complete') return; setShowCompletion(false); const timer = window.setTimeout(() => setShowCompletion(true), 2600); return () => window.clearTimeout(timer) }, [step])
  const addFiles = async (files: FileList | File[]) => { const items = Array.from(files); for (const file of items) { const queued: Statement = { id: crypto.randomUUID(), fileName: file.name, status: 'processing', transactionCount: 0, fileSize: file.size, fingerprint: `${file.name.toLowerCase()}-${file.size}-${file.lastModified}`, sourceFile: file }; setImports(current => [...current, { statement: queued, transactions: [] }]); const result = await processStatement(file, accounts, categories, [...importedStatements.map(s=>s.fingerprint), ...imports.map(i=>i.statement.fingerprint)]); const resultWithSource = { ...result, statement: { ...result.statement, sourceFile: file } }; setImports(current => current.map(item => item.statement.id === queued.id ? resultWithSource : item)); } setShowImportNext(false); if (tourStep === 'import-dropzone') onTourStep?.('import-confirm') }
  const remove = (id: string) => setImports(current => current.filter(item => item.statement.id !== id))
  const removeTransaction = (id: string) => setImports(current => current.map(item => ({ ...item, transactions: item.transactions.filter(review => review.transaction.id !== id) })))
  const updateReview = (id: string, key: 'merchantNormalized'|'amount'|'transactionDate'|'transactionType'|'categoryId'|'accountId', value: string) => setImports(current => current.map(item => ({ ...item, transactions: item.transactions.map(review => review.transaction.id === id ? { ...review, transaction: { ...review.transaction, [key]: key === 'amount' ? Number(value) : value }, flags: review.flags.filter(flag => !((key === 'merchantNormalized' && flag.field === 'merchant') || (key === 'amount' && flag.field === 'amount') || (key === 'transactionDate' && flag.field === 'date') || (key === 'accountId' && flag.field === 'account') || (key === 'categoryId' && flag.field === 'category'))) } : review) })))
  const reviewTransactions = imports.flatMap(i => i.transactions); const importable = imports.filter(i => i.statement.status === 'ready' || i.statement.status === 'warning'); const flags = reviewTransactions.flatMap(t => t.flags); const continueReview = () => setStep('review'); const confirm = () => { onComplete(reviewTransactions, importable.map(i => ({ ...i.statement, status: 'imported', importedAt: new Date().toISOString() }))); if (tourStep === 'import-confirm') onTourStep?.('import-dashboard'); setImportedCount(reviewTransactions.length); setStep('complete') }
  const leaveCompletion = () => { onBack(); onTourStep?.(tourScope === 'current' ? 'idle' : 'dashboard-hide-numbers') }
  const handleTourNext = () => {
    if (tourStep === 'import-dropzone') {
      // Let Next perform the same action as clicking the highlighted drop
      // zone.  The native file picker remains user-controlled; once files
      // finish processing, addFiles advances the tour to import-confirm.
      if (!imports.length || showImportNext) {
        setShowImportNext(false)
        document.querySelector<HTMLElement>('[data-tour="import-dropzone"]')?.click()
      }
      return
    }
    if (tourStep === 'import-confirm' && importable.length > 0) {
      // Confirm through the real button so all existing import/completion
      // behavior remains in one path.
      document.querySelector<HTMLElement>('[data-tour="import-confirm"]')?.click()
      return
    }
    if (tourStep === 'import-dashboard') {
      // The completion screen's View dashboard button owns the transition
      // back to the dashboard and the first dashboard-tour step.
      document.querySelector<HTMLElement>('[data-tour="import-dashboard"]')?.click()
    }
  }
  const handleTourBack = () => { if (tourStep === 'import-dropzone') { setShowImportNext(false); onTourBack?.(); return } if (tourStep === 'import-confirm') { setStep('upload'); setShowImportNext(true); onTourStep?.('import-dropzone'); return } if (tourStep === 'import-dashboard') { setShowCompletion(false); setStep('upload'); setShowImportNext(false); onTourStep?.('import-confirm') } }
  const startImportTour = (scope: 'full'|'current') => { if (step !== 'upload') setStep('upload'); setShowCompletion(false); setShowImportNext(false); onTourStart?.(scope); if (scope === 'current') onTourStep?.('import-dropzone') }
  // The import flow is the onboarding entry point, so only the full-site
  // tour is offered here. The current-page tour appears once the dashboard
  // shell has loaded and a page context exists.
  const tourLinks = <div className="import-tour-links" aria-label="Tours"><button type="button" onClick={() => startImportTour('full')}>Tour of entire website</button></div>
  if (step === 'complete') return <div className="import-page"><button className="back-button" onClick={leaveCompletion}><ArrowLeft size={17}/>Back to dashboard</button><div className={`complete-state ${showCompletion ? '' : 'thank-you-completion'}`}>{showCompletion ? <><h1 className="completion-copy">Your spending story is ready.</h1><p className="completion-copy">Added {importedCount} normalized transactions from {importable.length} statement{importable.length === 1 ? '' : 's'}.</p><div className="completion-actions completion-copy"><button className="import-button" data-tour="import-dashboard" onClick={leaveCompletion}>View dashboard <ArrowRight size={16}/></button></div></> : <CompletionCelebration />}</div>{tourLinks}<OnboardingTour step={tourStep} onSkip={onTourSkip ?? (() => undefined)} onNext={handleTourNext} onBack={handleTourBack} showImportNext={showImportNext}/></div>
  return <div className="import-page"><button className="back-button" onClick={onBack}><ArrowLeft size={17}/>Back to dashboard</button><div className="import-heading"><p className="eyebrow">STATEMENT IMPORT</p><h1>{step === 'review' ? 'Review your import' : 'Import your statements'}</h1><p>{step === 'review' ? 'A quick check before these transactions join your unified spending view.' : "Upload statements from your cards or bank accounts and we'll organize them into one clear spending view."}</p></div><input ref={picker} className="sr-only" type="file" multiple accept=".csv,.xlsx,.xls,.pdf" onChange={e => e.target.files && addFiles(e.target.files)} />
    {step === 'upload' && <><button className={`drop-zone ${dragging ? 'dragging' : ''}`} data-tour="import-dropzone" onClick={() => picker.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}}><span className="upload-orb"><Upload size={25}/></span><strong>Drop your statements here</strong><span>or <u>browse files</u> from your device</span><small>CSV, XLSX, and text-based PDFs are processed locally. Ambiguous PDFs are flagged for review.</small></button>{imports.length > 0 && <><section className="import-list panel"><div className="section-head"><div><h2>{imports.length} file{imports.length === 1 ? '' : 's'} selected</h2><p className="muted">Files stay in this session and are never saved to your browser.</p></div><button className="add-more" onClick={() => picker.current?.click()}><Plus size={16}/>Add files</button></div>{imports.map(({ statement }) => <FileRow key={statement.id} statement={statement} onRemove={()=>remove(statement.id)} />)}</section><div className="import-footer"><span><ShieldCheck size={17}/>Private processing in your browser</span><div className="import-actions"><button disabled={!importable.length} className="secondary-button" onClick={continueReview}>Review import</button><button disabled={!importable.length} className="import-button" data-tour="import-confirm" onClick={confirm}>Import data for dashboard <Check size={16}/></button></div></div></>}</>}
    {step === 'review' && <><section className="review-summary"><div><strong>{imports.length} statements processed</strong><span>{reviewTransactions.length} transactions detected</span></div><div><strong>{reviewTransactions.length - flags.length} ready</strong><span>{flags.length} items need attention</span></div><div><strong>{importable.length} accounts matched</strong><span>Payments excluded from spend</span></div></section><section className="import-list panel"><div className="section-head"><div><p className="eyebrow">STATEMENTS</p><h2>Import summary</h2></div><button className="add-more" onClick={() => picker.current?.click()}><Plus size={16}/>Add files</button></div>{imports.map(({ statement }) => <FileRow key={statement.id} statement={statement} onRemove={()=>remove(statement.id)} />)}</section><div className="review-scroll-area"><section className="review-table panel"><div className="section-head compact"><div><p className="eyebrow">TRANSACTIONS</p><h2>Review imported data</h2></div><span className="review-count">{reviewTransactions.length} transactions</span></div>{reviewTransactions.map(review => <ReviewRow key={review.transaction.id} review={review} accounts={accounts} categories={categories} onChange={updateReview} onDelete={removeTransaction}/>)}</section><button className="review-scroll-control review-scroll-down" aria-label="Jump to import" title="Jump to import" onClick={()=>reviewBottom.current?.scrollIntoView({ behavior:'smooth', block:'end' })}><ChevronDown size={18}/></button><div className="import-footer" ref={reviewBottom}><button className="secondary-button" onClick={()=>setStep('upload')}><ArrowLeft size={15}/>Back</button><button disabled={!importable.length} className="import-button" data-tour="import-confirm" onClick={confirm}>Import {reviewTransactions.length} transactions <Check size={16}/></button></div><button className="review-scroll-control review-scroll-up" aria-label="Back to review header" title="Back to review header" onClick={()=>window.scrollTo({ top:0, behavior:'smooth' })}><ChevronUp size={18}/></button></div></>}
    {tourLinks}<OnboardingTour step={tourStep} onSkip={onTourSkip ?? (() => undefined)} onNext={handleTourNext} onBack={handleTourBack} showImportNext={showImportNext}/>
  </div>
}
function CompletionCelebration() {
  return <div className="thank-you-state" role="status" aria-live="polite"><h1 className="thank-you-heading" aria-label="Thank You for Trusting My Project"><span>Thank You for Trusting</span><span>My Project</span></h1><p className="thank-you-signature is-visible">— Swagat Karki</p></div>
}
function FileRow({ statement, onRemove }: { statement: Statement; onRemove: ()=>void }) { const icon = statement.status === 'failed' || statement.status === 'duplicate' ? <FileWarning/> : statement.status === 'processing' ? <LoaderCircle className="spin"/> : <FileSpreadsheet/>; return <div className="import-file"><span className={`file-icon ${statement.status}`}>{icon}</span><div className="file-info"><strong>{statement.fileName}</strong><small>{fileSize(statement.fileSize)} · {statement.institution ? `${statement.institution} · ` : ''}{statement.documentType ? statement.documentType.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, char => char.toUpperCase()) : statement.parser ?? 'Detecting format'} {statement.transactionCount ? `· ${statement.transactionCount} transactions` : ''}</small>{statement.message && <em>{statement.message}</em>}</div><span className={`status-badge ${statement.status}`}>{statement.status === 'ready' && <CheckCircle2 size={13}/>} {statement.status === 'warning' && <AlertTriangle size={13}/>} {labels[statement.status]}</span>{statement.status === 'failed' ? <button className="row-action" title="Try again"><RotateCcw size={16}/></button> : <button className="row-action" onClick={onRemove} title="Remove"><Trash2 size={16}/></button>}</div> }
function ReviewRow({ review, accounts, categories, onChange, onDelete }: { review: ReviewTransaction; accounts: Account[]; categories: Category[]; onChange: (id: string, key: 'merchantNormalized'|'amount'|'transactionDate'|'transactionType'|'categoryId'|'accountId', value: string)=>void; onDelete: (id: string)=>void }) { const t=review.transaction; return <div className="review-row"><div><input aria-label="Date" value={t.transactionDate} onChange={e=>onChange(t.id,'transactionDate',e.target.value)}/><small>{review.flags.find(f=>f.field==='date')?.message}</small></div><div><input aria-label="Merchant" value={t.merchantNormalized} onChange={e=>onChange(t.id,'merchantNormalized',e.target.value)}/><small>{review.flags.find(f=>f.field==='merchant')?.message}</small></div><div><input aria-label="Amount" value={t.amount} onChange={e=>onChange(t.id,'amount',e.target.value)}/><small>{review.flags.find(f=>f.field==='amount')?.message}</small></div><select aria-label="Account" value={t.accountId} onChange={e=>onChange(t.id,'accountId',e.target.value)}><option value="unassigned">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</select><select aria-label="Category" value={t.categoryId} onChange={e=>onChange(t.id,'categoryId',e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="delete-transaction" aria-label={`Delete ${t.merchantNormalized}`} onClick={()=>onDelete(t.id)}><Trash2 size={15}/></button></div> }
