import { useMemo, useState } from 'react'
import { ArrowUpRight, Maximize2, Search, Store, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts'
import type { Account, Transaction } from '../data/models'
import { categories } from '../data/mockData'
import DateRangePicker from './DateRangePicker'
import { buildMerchantAnalytics, merchantAccountName, merchantTimeSeries, type MerchantAggregate } from '../services/merchantAnalytics'
import { spendingAmount } from '../services/statementImport'
import { cardLogoFor } from '../utils/cardLogo'

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })

type Props = { transactions: Transaction[]; availableAccounts: Account[]; dates: string[]; months: string[]; mode: string; start: string; end: string; openRequest: number; onDateChange: (mode: string, start?: string, end?: string) => void; onImport: () => void }
type SortMode = 'spending' | 'frequency' | 'average' | 'alpha'

function MerchantScatterTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload?: MerchantAggregate & { x: number; y: number } }> }) {
  const merchant = payload?.[0]?.payload
  if (!active || !merchant) return null
  return <div className="merchant-scatter-tooltip"><strong>{merchant.name}</strong><span className={merchant.total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.total)} total</span><span>{merchant.transactionCount} transactions</span><span className={merchant.averageTransaction < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.averageTransaction)} average</span><span>{merchant.cardsUsed} card{merchant.cardsUsed === 1 ? '' : 's'} used</span><small>{merchant.category}</small></div>
}

function MerchantScatterPlot({ merchants, onSelect }: { merchants: MerchantAggregate[]; onSelect: (merchant: MerchantAggregate) => void }) {
  return <ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 18, bottom: 18, left: 4 }}><CartesianGrid stroke="#efeff4" strokeDasharray="3 5"/><XAxis type="number" dataKey="x" name="Transactions" tick={{ fill: '#8e8d9d', fontSize: 10 }} allowDecimals={false} label={{ value: 'Transactions', position: 'insideBottom', offset: -10, fill: '#9997a4', fontSize: 10 }}/><YAxis type="number" dataKey="y" name="Spending" tick={{ fill: '#8e8d9d', fontSize: 10 }} tickFormatter={value => `$${Math.round(Number(value))}`} label={{ value: 'Spending', angle: -90, position: 'insideLeft', fill: '#9997a4', fontSize: 10 }}/><Tooltip content={<MerchantScatterTooltip/>}/><Scatter data={merchants.map(merchant => ({ ...merchant, x: merchant.transactionCount, y: merchant.total }))} fill="#5763d7" onClick={(point: unknown) => { const payload = typeof point === 'object' && point !== null ? point as { id?: unknown; payload?: { id?: unknown } } : {}; const merchantId = String(payload.id ?? payload.payload?.id ?? ''); const merchant = merchants.find(candidate => candidate.id === merchantId); if (merchant) onSelect(merchant) }}/></ScatterChart></ResponsiveContainer>
}

function MerchantDetailDrawer({ merchant, accountId, accounts, onClose }: { merchant: MerchantAggregate; accountId?: string; accounts: Account[]; onClose: () => void }) {
  const transactions = accountId ? merchant.transactions.filter(transaction => transaction.accountId === accountId) : merchant.transactions
  const total = transactions.reduce((sum, transaction) => sum + spendingAmount(transaction), 0)
  const average = transactions.length ? total / transactions.length : 0
  const cardRows = Object.entries(merchant.amountByCard).map(([id, amount]) => ({ id, amount, count: merchant.countByCard[id] ?? 0 })).filter(row => !accountId || row.id === accountId).sort((first, second) => second.amount - first.amount)
  const cardTransactionRows = cardRows.map(row => ({ ...row, transactions: transactions.filter(transaction => transaction.accountId === row.id) })).filter(row => row.transactions.length)
  const primary = cardRows[0]
  const series = merchantTimeSeries({ ...merchant, transactions: accountId ? transactions : merchant.transactions })
  const maxSeries = Math.max(...series.map(point => point.amount), 0)
  return <div className="merchant-detail-backdrop" role="presentation" onMouseDown={onClose}><aside className="merchant-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="merchant-detail-title" onMouseDown={event => event.stopPropagation()}>
    <header className="merchant-detail-header"><div><p className="eyebrow">MERCHANT DETAIL</p><h2 id="merchant-detail-title">{merchant.name}</h2><p>{merchant.category}{accountId ? ` · ${merchantAccountName(accountId, accounts)}` : ''}</p></div><button className="modal-close" aria-label="Close merchant details" onClick={onClose}><X size={18}/></button></header>
    <div className="merchant-detail-kpis"><div><small>Total spending</small><strong className={total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(total)}</strong></div><div><small>Transactions</small><strong>{transactions.length}</strong></div><div><small>Average</small><strong className={average < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(average)}</strong></div><div><small>Cards used</small><strong>{cardRows.length}</strong></div></div>
    {cardRows.length > 1 && <section className="merchant-detail-section"><div className="merchant-detail-section-heading"><h3>Card usage</h3><small>{cardRows.length} cards in this view</small></div><div className="merchant-detail-card-usage">{cardRows.map(row => <button className="merchant-detail-card-row" type="button" key={row.id} onClick={() => document.getElementById(`merchant-transactions-${row.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })} aria-label={`Show ${merchantAccountName(row.id, accounts)} transactions`}><span className="merchant-detail-card-title">{cardLogoFor(accounts.find(account => account.id === row.id)?.institution ?? '') && <img src={cardLogoFor(accounts.find(account => account.id === row.id)?.institution ?? '')!} alt=""/>}<span><strong>{merchantAccountName(row.id, accounts)}</strong><small>{row.count} transaction{row.count === 1 ? '' : 's'}</small></span></span><b className={row.amount < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(row.amount)}</b><i><span style={{ width: `${primary?.amount ? row.amount / primary.amount * 100 : 0}%` }}/></i></button>)}</div></section>}
    <section className="merchant-detail-section"><div className="merchant-detail-section-heading"><h3>Spending over time</h3></div>{series.length ? <div className="merchant-detail-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="merchant-detail-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5763d7" stopOpacity=".2"/><stop offset="100%" stopColor="#5763d7" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#efeff4" strokeDasharray="3 5"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#8e8d9d', fontSize: 10 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#aaa8b4', fontSize: 10 }} tickFormatter={value => `$${Math.round(Number(value))}`} width={45}/><Tooltip formatter={(value) => money.format(Number(value))}/><Area type="monotone" dataKey="amount" stroke="#5763d7" strokeWidth={2.3} fill="url(#merchant-detail-fill)" dot={{ r: 3, fill: '#5763d7', stroke: '#fff', strokeWidth: 1.5 }}/></AreaChart></ResponsiveContainer></div> : <p className="merchant-detail-empty">No dated spending transactions.</p>}</section>
    <section className="merchant-detail-section"><div className="merchant-detail-section-heading"><h3>Transactions</h3><small>{transactions.length} shown</small></div><div className="merchant-detail-transaction-groups">{cardTransactionRows.map(row => { const logo = cardLogoFor(accounts.find(account => account.id === row.id)?.institution ?? ''); return <section className="merchant-detail-transaction-group" id={`merchant-transactions-${row.id}`} key={`merchant-transactions-${row.id}`}><div className="merchant-detail-transaction-group-heading"><div className="merchant-detail-card-title">{logo && <img src={logo} alt=""/>}<span><strong>{merchantAccountName(row.id, accounts)}</strong><small>{row.count} transaction{row.count === 1 ? '' : 's'}</small></span></div><b className={row.amount < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(row.amount)}</b></div><div className="merchant-detail-transactions">{row.transactions.slice().sort((first, second) => second.transactionDate.localeCompare(first.transactionDate)).map(transaction => <div className="merchant-detail-transaction" key={transaction.id}><div><strong>{transaction.description || transaction.merchantRaw}</strong><small>{transaction.transactionDate || 'Date unavailable'}</small></div><b className={transaction.amount < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(transaction.amount)}</b></div>)}</div></section>})}</div></section>
  </aside></div>
}

export default function MerchantsView({ transactions, availableAccounts, dates, months, mode, start, end, openRequest, onDateChange, onImport }: Props) {
  const [search, setSearch] = useState('')
  const [sort, setSort] = useState<SortMode>('spending')
  const [visibleLimit, setVisibleLimit] = useState(10)
  const [heatmapLimit, setHeatmapLimit] = useState(10)
  const [selectedMerchant, setSelectedMerchant] = useState<MerchantAggregate | null>(null)
  const [selectedAccountId, setSelectedAccountId] = useState<string | undefined>()
  const [scatterExpanded, setScatterExpanded] = useState(false)
  const [frequencyExpanded, setFrequencyExpanded] = useState(false)
  const [hoveredMerchantId, setHoveredMerchantId] = useState<string | null>(null)
  const [hoveredCell, setHoveredCell] = useState<{ merchantId: string; accountId: string } | null>(null)
  const analytics = useMemo(() => buildMerchantAnalytics(transactions, availableAccounts, categories), [transactions, availableAccounts])
  const merchants = analytics.merchants
  const sortedDirectory = useMemo(() => merchants.filter(merchant => merchant.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).slice().sort((first, second) => sort === 'frequency' ? second.transactionCount - first.transactionCount : sort === 'average' ? second.averageTransaction - first.averageTransaction : sort === 'alpha' ? first.name.localeCompare(second.name) : second.total - first.total), [merchants, search, sort])
  const frequentMerchants = useMemo(() => merchants.slice().sort((first, second) => second.transactionCount - first.transactionCount || second.total - first.total), [merchants])
  const heatmapMerchants = merchants.slice(0, heatmapLimit)
  const scatterMerchants = merchants.slice(0, 25)
  const openMerchant = (merchant: MerchantAggregate, accountId?: string) => { setSelectedMerchant(merchant); setSelectedAccountId(accountId) }
  const accountColumns = availableAccounts.filter(account => merchants.some(merchant => merchant.amountByCard[account.id] !== undefined))
  const categoryFor = (merchant: MerchantAggregate) => merchant.category
  if (!merchants.length) return <div className="merchants-view"><header className="merchants-view-header"><div><h1>Merchants</h1><p className="subhead">Understand where your money is going across your cards.</p></div><div className="header-actions">{dates.length > 0 && <DateRangePicker dates={dates} months={months} mode={mode} start={start} end={end} openRequest={openRequest} onChange={onDateChange}/>}<button className="import-button" onClick={onImport}>Import statements</button></div></header><section className="empty-dashboard merchants-empty"><span className="upload-orb"><Store size={24}/></span><h2>No merchants yet</h2><p>Import a statement to see where your money is going.</p><button className="import-button" onClick={onImport}>Import statements</button></section></div>
  return <div className="merchants-view"><header className="merchants-view-header"><div><h1>Merchants</h1><p className="subhead">Understand where your money is going across your cards.</p></div><div className="header-actions">{dates.length > 0 && <DateRangePicker dates={dates} months={months} mode={mode} start={start} end={end} openRequest={openRequest} onChange={onDateChange}/>}<button className="import-button" onClick={onImport}>Import statements</button></div></header>
    <section className="merchant-overview-grid"><section className="merchant-panel merchant-top-panel"><div className="merchant-panel-heading"><div><h2>Top merchants</h2></div><select value={visibleLimit} onChange={event => setVisibleLimit(Number(event.target.value))} aria-label="Top merchant count"><option value={10}>Top 10</option><option value={25}>Top 25</option><option value={50}>Top 50</option></select></div><div className="merchant-ranking-list">{merchants.slice(0, visibleLimit).map((merchant, index) => <button className="merchant-analytics-row" key={merchant.id} onClick={() => openMerchant(merchant)} onMouseEnter={() => setHoveredMerchantId(merchant.id)} onMouseLeave={() => setHoveredMerchantId(null)}><span className={`merchant-analytics-rank ${index === 0 ? 'top' : ''}`}>{index + 1}</span><span className="merchant-analytics-copy"><strong>{merchant.name}</strong><small>{merchant.transactionCount} transaction{merchant.transactionCount === 1 ? '' : 's'} · {merchant.cardsUsed} card{merchant.cardsUsed === 1 ? '' : 's'}</small><i><span style={{ width: `${merchants[0]?.total ? merchant.total / merchants[0].total * 100 : 0}%` }}/></i></span><b className={merchant.total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.total)}</b><ArrowUpRight size={15}/>{hoveredMerchantId === merchant.id && <span className="merchant-hover-tooltip"><strong>{merchant.name}</strong><span className={merchant.total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.total)} total</span><span>{merchant.transactionCount} transactions · {merchant.cardsUsed} cards used</span><small className={merchant.averageTransaction < 0 ? 'amount-negative' : 'amount-positive'}>Average: {money.format(merchant.averageTransaction)}</small></span>}</button>)}</div></section></section>
    <section className="merchant-panel merchant-heatmap-panel"><div className="merchant-panel-heading"><div><h2>Merchant by Card</h2></div><select value={heatmapLimit} onChange={event => setHeatmapLimit(Number(event.target.value))} aria-label="Merchant count"><option value={10}>Top 10</option><option value={25}>Top 25</option><option value={50}>Top 50</option></select></div><div className="merchant-heatmap-scroll"><table className="merchant-heatmap"><thead><tr><th>Merchant</th>{accountColumns.map(account => <th key={account.id}>{cardLogoFor(account.institution) && <img src={cardLogoFor(account.institution)!} alt=""/>}<span>{account.institution}</span></th>)}</tr></thead><tbody>{heatmapMerchants.map(merchant => <tr key={merchant.id}><th scope="row"><button onClick={() => openMerchant(merchant)}>{merchant.name}</button></th>{accountColumns.map(account => { const amount = merchant.amountByCard[account.id] ?? 0; const intensity = analytics.byCardTotal[account.id] ? .08 + Math.min(.38, amount / analytics.byCardTotal[account.id] * .38) : 0; const tint = `${account.color}${Math.round((amount ? .12 + intensity * .28 : .04) * 255).toString(16).padStart(2, '0')}`; const isHovered = hoveredCell?.merchantId === merchant.id && hoveredCell.accountId === account.id; return <td key={account.id}><button className={amount ? (amount < 0 ? 'amount-negative' : 'amount-positive') : 'empty'} style={amount ? { background: tint, borderColor: `${account.color}38` } : undefined} onMouseEnter={() => amount && setHoveredCell({ merchantId: merchant.id, accountId: account.id })} onMouseLeave={() => setHoveredCell(null)} onClick={() => amount && openMerchant(merchant, account.id)} aria-label={amount ? `${account.institution}, ${merchant.name}, ${money.format(amount)}, ${merchant.countByCard[account.id] ?? 0} transactions` : `${account.institution}, no spending at ${merchant.name}`}>{amount ? money.format(amount) : '—'}</button>{isHovered && <span className="merchant-hover-tooltip merchant-heatmap-tooltip"><strong>{merchant.name}</strong><span className={amount < 0 ? 'amount-negative' : 'amount-positive'}>{account.institution}: {money.format(amount)}</span><small>{merchant.countByCard[account.id] ?? 0} transaction{merchant.countByCard[account.id] === 1 ? '' : 's'}</small></span>}</td>})}</tr>)}</tbody></table></div></section>
    <section className="merchant-behavior-grid"><section className="merchant-panel merchant-scatter-panel"><div className="merchant-panel-heading"><div><h2>Frequency vs spending</h2><p>Each dot is a merchant.</p></div><button className="merchant-expand-button" aria-label="Enlarge frequency versus spending chart" onClick={() => setScatterExpanded(true)}><Maximize2 size={15}/></button></div><div className="merchant-scatter"><MerchantScatterPlot merchants={scatterMerchants} onSelect={openMerchant}/></div></section><section className="merchant-panel merchant-frequency-panel"><div className="merchant-panel-heading"><div><h2>Most frequent merchants</h2></div><button className="text-button" onClick={() => setFrequencyExpanded(true)}>View all</button></div><div className="merchant-frequency-list">{frequentMerchants.slice(0, 5).map(merchant => <button key={merchant.id} onClick={() => openMerchant(merchant)}><span><strong>{merchant.name}</strong><small>{merchant.cardsUsed} card{merchant.cardsUsed === 1 ? '' : 's'}</small></span><b>{merchant.transactionCount}</b></button>)}</div></section></section>
    <section className="merchant-panel merchant-directory-panel"><div className="merchant-panel-heading"><div><h2>All merchants</h2><p>{sortedDirectory.length} merchant{sortedDirectory.length === 1 ? '' : 's'} in the current view.</p></div><div className="merchant-directory-controls"><label><Search size={15}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search merchants..."/></label><select value={sort} onChange={event => setSort(event.target.value as SortMode)} aria-label="Sort merchants"><option value="spending">Highest spending</option><option value="frequency">Most transactions</option><option value="average">Highest average</option><option value="alpha">Alphabetical</option></select></div></div><div className="merchant-directory-list">{sortedDirectory.map(merchant => <button className="merchant-directory-row" key={merchant.id} onClick={() => openMerchant(merchant)}><span><strong>{merchant.name}</strong><small>{categoryFor(merchant)} · {merchant.transactionCount} transaction{merchant.transactionCount === 1 ? '' : 's'}</small></span><b className={merchant.total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.total)}</b><span className="merchant-directory-cards">{merchant.cardsUsed} card{merchant.cardsUsed === 1 ? '' : 's'}</span><span className="merchant-directory-average">{money.format(merchant.averageTransaction)} avg.</span><ArrowUpRight size={15}/></button>)}{!sortedDirectory.length && <div className="merchant-directory-empty">No merchants match “{search}”.</div>}</div></section>
    {scatterExpanded && <div className="merchant-chart-modal-backdrop" role="presentation" onMouseDown={() => setScatterExpanded(false)}><section className="merchant-chart-modal" role="dialog" aria-modal="true" aria-labelledby="merchant-scatter-modal-title" onMouseDown={event => event.stopPropagation()}><header><div><p className="eyebrow">MERCHANT ANALYTICS</p><h2 id="merchant-scatter-modal-title">Frequency vs spending</h2><p>Click any dot to view that merchant's transactions.</p></div><button className="modal-close merchant-chart-modal-close" aria-label="Close enlarged chart" onClick={() => setScatterExpanded(false)}><X size={18}/></button></header><div className="merchant-scatter-expanded"><MerchantScatterPlot merchants={scatterMerchants} onSelect={openMerchant}/></div></section></div>}
    {frequencyExpanded && <div className="merchant-frequency-modal-backdrop" role="presentation" onMouseDown={() => setFrequencyExpanded(false)}><section className="merchant-frequency-modal" role="dialog" aria-modal="true" aria-labelledby="merchant-frequency-modal-title" onMouseDown={event => event.stopPropagation()}><header><div><p className="eyebrow">MERCHANT ANALYTICS</p><h2 id="merchant-frequency-modal-title">Most frequent merchants</h2><p>All merchants in the current view, ranked by number of visits.</p></div><button className="modal-close merchant-chart-modal-close" aria-label="Close most frequent merchants" onClick={() => setFrequencyExpanded(false)}><X size={18}/></button></header><div className="merchant-frequency-modal-list">{frequentMerchants.map((merchant, index) => <button key={merchant.id} className="merchant-frequency-modal-row" onClick={() => { setFrequencyExpanded(false); openMerchant(merchant) }}><span className="merchant-frequency-modal-rank">{index + 1}</span><span className="merchant-frequency-modal-copy"><strong>{merchant.name}</strong><small>{merchant.category} · {merchant.cardsUsed} card{merchant.cardsUsed === 1 ? '' : 's'}</small></span><span className="merchant-frequency-modal-metrics"><b>{merchant.transactionCount} visit{merchant.transactionCount === 1 ? '' : 's'}</b><small className={merchant.total < 0 ? 'amount-negative' : 'amount-positive'}>{money.format(merchant.total)} total · Avg. {money.format(merchant.averageTransaction)}</small></span><ArrowUpRight size={15}/></button>)}</div></section></div>}
    {selectedMerchant && <MerchantDetailDrawer merchant={selectedMerchant} accountId={selectedAccountId} accounts={availableAccounts} onClose={() => { setSelectedMerchant(null); setSelectedAccountId(undefined) }}/>} 
  </div>
}
